theme: jekyll-theme-tactile
title: Open source bioreactor
description: The open-source bioreactor is a project between univalle, epfl and hackuarium in order to create a bioreactor available to everybody
source:docs_source
destination:docs

